/*
  Warnings:

  - Added the required column `updatedAt` to the `Message` table without a default value. This is not possible if the table is not empty.
  - Added the required column `updatedAt` to the `Participant` table without a default value. This is not possible if the table is not empty.

*/
-- === MESSAGE ===
-- Add updatedAt with a default so existing rows pass NOT NULL
ALTER TABLE "Message"
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Optional: if you want historical accuracy, align updatedAt to createdAt for old rows
UPDATE "Message"
SET "updatedAt" = "createdAt"
WHERE "updatedAt" IS NOT NULL; -- it will be NOT NULL due to default, so skip or leave as-is

-- Drop the default so Prisma controls it via @updatedAt
ALTER TABLE "Message"
  ALTER COLUMN "updatedAt" DROP DEFAULT;


-- === PARTICIPANT ===
-- Add createdAt (if your table didn’t have it)
ALTER TABLE "Participant"
  ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Add updatedAt with default for backfill
ALTER TABLE "Participant"
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- New flags (if they didn't exist previously)
ALTER TABLE "Participant"
  ADD COLUMN "isMuted"   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN "isBlocked" BOOLEAN NOT NULL DEFAULT FALSE;

-- Align updatedAt to createdAt for old rows (optional but neat)
UPDATE "Participant"
SET "updatedAt" = "createdAt";

-- Keep default on createdAt, but drop on updatedAt so @updatedAt manages it
ALTER TABLE "Participant"
  ALTER COLUMN "updatedAt" DROP DEFAULT;


-- === INDEXES (only add if they’re not already in the autogenerated SQL) ===
-- Messages: (senderId, createdAt)
CREATE INDEX IF NOT EXISTS "Message_senderId_createdAt_idx"
ON "Message" ("senderId", "createdAt");

-- Conversations: (lastMessageAt)
CREATE INDEX IF NOT EXISTS "Conversation_lastMessageAt_idx"
ON "Conversation" ("lastMessageAt");
